# =================================================================================================
#     Project settings
# =================================================================================================
# Project variables.
project:

  # ----------------------------------------------------------------------
  #     Meta-variables
  # ----------------------------------------------------------------------
  # Variables such as the project name.
  meta: 

    # [Optional] The name of the project. 
    # You can name it anything you'd like, but we recommend a descriptive name including
    # a project identifier, if it has one. 
    # If you provide a project name and/or a run name and not an output directory (output_dir, below),
    # the pipeline will use the project name in building an output directory:
    # [{project_name}_][{run_name}_]{YEAR}-{MONTH}-{DAY}-{HOUR}-{MINUTE}
    project_name: DSP-016_Sarcoma-characterization

    # [Optional] A name for this run.
    # You can name it anything you'd like. 
    # For example, if you're just running the QC, maybe name it
    # "QC" or something like that.
    # If provided, it will be used in naming some of the files.
    # You can leave it blank, too.
    # If you provide a project name and/or a run name and not an output directory (output_dir, below),
    # the pipeline will use the project name in building an output directory:
    # [{project_name}_][{run_name}_]{YEAR}-{MONTH}-{DAY}-{HOUR}-{MINUTE}
    run_name: segment-QC

  # ----------------------------------------------------------------------
  #     Technical
  # ----------------------------------------------------------------------
  technical:

    # [Required] Absolute path to the binary for the R package "regexPipes" (v. 0.0.1).
    path_to_regexPipes: /Users/lwfong/OneDrive - Inside MD Anderson/PRIME-TR_projects/LFI-001_bisantine-geo/ext/regexPipes_0.0.1_r-release-x86_64.tgz
  
# =================================================================================================
#     Inputs
# =================================================================================================
# Paths to input data. Use absolute (full) paths, not relative paths.
data:

  # [Required] Absolute path to the directory containing the DCC files.
  dcc_dir: /Users/lwfong/OneDrive - Inside MD Anderson/PRIME-TR_projects/LFC-013_Sarcoma-characterization/data/processed_data/GeoMx/

  # [Required] Absolute path to the directory containing the PKC files.
  pkc_dir: /Users/lwfong/OneDrive - Inside MD Anderson/PRIME-TR_projects/Common/GeoMx/PKC_files/

  # [Optional] Regular expression (regex) pattern indicating which PKC files to use.
  # If left blank, will use all files matching \\.pkc$
  pkc_filename_pattern: Hs_R_NGS_WTA_v1.0.pkc$

  # [Required] Absolute path to the Microsoft Excel (.xlsx) file containing the phenodata/sample annotation.
  sample_annotation_file: /Users/lwfong/OneDrive - Inside MD Anderson/PRIME-TR_projects/LFC-013_Sarcoma-characterization/data/processed_data/GeoMx/2024-02-19 Annotations.xlsx

  # [Optional] Name of the sheet in the Excel file (given in sample_annotation_file) containing the phenodata. 
  # If not provided, the pipeline will use the first sheet in the Excel file.
  phenodata_sheet_name: Annotations

  # [Optional] Absolute path to the PowerPoint file to be used as a template in generating the output PowerPoint.
  # If not provided, the pipeline will use the default PowerPoint template. 
  # If you already have a PowerPoint generated from previous runs, you can enter that
  # and the pipeline will build on it. 
  ppt_template_file: /Users/lwfong/OneDrive - Inside MD Anderson/Graphics/Presentation_templates/MD-Anderson_templates/MD Anderson_Standard_16x9_Template 2_PPT.pptx

  # [Optional] Absolute path to an output folder from a previous bisantine-geo run.
  # Allows the pipeline to "pick up" from where you left off. 
  # If provided, the pipeline will use the output Rds and PowerPoint files from this folder.
  # NOTE: this parameter overrides the ppt_template_file parameter above.
  # Also, if you have more than one PowerPoint file in the pubs/ subdirectory of this folder,
  # the pipeline will only use the first one. (So don't have more than one.)
  previous_run_out_dir: 

# =================================================================================================
#     Outputs
# =================================================================================================
# Output paths, using absolute file paths.
output:

  # [Optional] Absolute path to the directory in which to save output files.
  # If not provided, the pipeline will create the following directory and save save output files to it: 
  #   ./out/[{project_name}_][{run_name}_]{YEAR}-{MONTH}-{DAY}-{HOUR}-{MINUTE}/
  # For further information about the nomenclature of output files, see the ./docs folder. 
  output_dir:

# =================================================================================================
#     Experiment settings
# =================================================================================================
# Experiment settings.
experiment:

  # ----------------------------------------------------------------------
  #     Annotation column names
  # ----------------------------------------------------------------------
  annotation: 

    # [Required] The column name in the sample annotation (given by {sample_annotation_file}) corresponding to
    # the DCC identifier.
    phenodata_dcc_col_name: Sample_ID

    # [Required] The column name(s) in the sample annotation (given by {sample_annotation_file}) corresponding to 
    # the protocol data column names.
    # Multiple values are allowed, separated by a comma (,).
    protocol_data_col_names: Aoi,Roi

    # [Required] The column name(s) in the sample annotation (given by {sample_annotation_file}) corresponding to 
    # the experiment data column names.
    experiment_data_col_names: Panel

  # ----------------------------------------------------------------------
  #     Segment QC settings
  # ----------------------------------------------------------------------
  segment_qc:
  
    # Settings for segment QC. Defaults are given in parentheses.
    # We recommend leaving the settings unchanged for the first pass, reviewing the QC outputs,
    # and then tweaking the settings accordingly for a second pass. 

    # [Required] Minimum number of reads for a given segment (1000)
    min_segment_reads: 1000 

    # [Required] Minimum % of reads trimmed (80%)
    percent_trimmed: 80 

    # [Required] Minimum % of reads stitched (80%)
    percent_stitched: 80  

    # [Required] Minimum % of reads aligned (80%)
    percent_aligned: 75    

    # [Required] Minimum sequencing saturation (50%)
    percent_saturation: 50 
    
    # [Required] Minimum negative control counts (10)
    # (The authors of this pipeline have found in our own data that 10 tends to be too stringent a cutoff.)
    min_negative_count: 1   
          
    # [Required] Maximum counts observed in NTC well (1000)
    max_ntc_count: 1000
          
    # [Required] Minimum # of nuclei estimated (100)
    min_nuclei: 100         
          
    # [Required] Minimum segment area (5000)
    min_area: 1000

  # ----------------------------------------------------------------------
  #     Probe QC settings
  # ----------------------------------------------------------------------
  probe_qc:

    # Settings for probe QC. Defaults are given in parentheses.
    
    # NOTE: it is recommended to leave the first two settings ({min_probe_ratio} and {percent_fail_grubss}) unchanged,
    # unless you really know what you're doing and have a compelling reason to change them.
    # A probe is removed GLOBALLY from the data set if it fails either of the following two cutoffs (below {min_probe_ratio}
    # or above {percent_fail_grubbs}).

    # [Required] Minimum ratio of (mean of probe i's counts) to (mean of all probe counts representing the same target in all segments) (0.1)
    min_probe_ratio: 0.1

    # [Required] Maximum percent of segments in which the probe fails the Grubb's test (20)
    percent_fail_grubbs: 20

    # The limit of quantification (LOQ) is an approximation of the quantifiable limit of gene expression per segment.
    # The LOQ for a particular segment i is given as 
    #   geomean(NegProbe_i) * geoSD(NegProbe_i)^n
    # where n is typically 2. 

    # [Required] Limit of quantification (LOQ) cutoff, i.e. the number of SDs above mean negative probe expression
    # a probe must be in order to be included. (2)
    # Below this, values will be thresholded to the minimum LOQ given below ({min_loq})
    loq_sd_cutoff: 2

    # [Required] Minimum limit of quantification (LOQ) (2) 
    # Values that fall below the cutoff given by {loq_sd_cutoff} are thresholded to this value. 
    min_loq: 2

    # In some of the segments, the gene detection rate (i.e. the % of genes that are above the LOQ)
    # is low compared to the other segments in the study.
    # We can filter out segments that fall below a specified gene detection rate (usually in the range 5 - 15%).
    # We can also filter out genes that don't appear in a specified minimum % of segments (usually in the range of 5 - 10%).
    
    # [Required] The minimum gene detection rate (given as a percent) that a segment must have to be kept (5)
    gene_detection_rate: 5

    # [Required] The percent of segments a gene must be detected in order to be kept (5)
    # We typically want to pick a cutoff that will leave us with at least 8000 genes.
    percent_of_segments: 5

  # ----------------------------------------------------------------------
  #     Normalization settings
  # ----------------------------------------------------------------------
  normalization:

    # [Optional] The normalization method to use.
    # If not provided, the pipeline will default to Q3 normalization.
    # Can be one of the following values: c("neg_norm", "q_norm")
    # where "neg_norm" indicates background normalization for WTA/CTA without custom spike-ins and
    # "q_norm" indicates Q3 (75th percentile) normalization for WTA/CTA with or without custom spike-ins.
    # We recommend using "neg_norm" if there is a good deal of overlap between the signal and noise probe distributions.
    normalization_method: q_norm

    # [Required] The annotation of interest (e.g. Segment, Region).
    ann_of_interest: Compartment

  # ----------------------------------------------------------------------
  #     Unsupervised analysis settings
  # ----------------------------------------------------------------------
  unsupervised:

    # [Optional] The column in the annotation to use as a grouping variable.
    # If provided, points on dimension reduction graphs (t-SNE, UMAP)
    # will be colored by group.
    compartment_var:

  # ----------------------------------------------------------------------
  #     Linear mixed models and differential expression
  # ----------------------------------------------------------------------
  lmm:

    # In this section there are four parameters for running linear mixed models (LMMs).
    # You can specify multiple experiments, as follows:
    # let's say you wanted to run two LMMs, 
    # the first: uses a random slope, 
    #   the test variable is named `Region` in the annotation, 
    #   the random intercept is the column `Sample ID` in the annotation,
    #   and the random slope is also `Region`;
    # the second: does NOT use a random slope,
    #   the test variable is named `Tissue Type` in the annotation,
    #   and the random intercept is `Sample ID`.
    # then you would fill out the four variables as follows:
    #
    # random_slope: yes,no
    # test_vars: Region,Tissue Type
    # random_intercept_vars: Sample ID,Sample ID
    # random_slope_vars: Region,NA        
    # 
    # NOTE: the number of values passed to each variable
    # must be the same across all the variables; otherwise,
    # values will be recycled to match the length of the longest variable. 

    # [Required] Whether or not to use a random slope in the linear mixed model.
    # The following values are allowed: c("yes", "no")
    random_slope: no

    # [Required] The column name(s) in the sample annotation (given by {sample_annotation_file}) corresponding to
    # the variables to be used for the test variable in the linear mixed models for differential expression.
    # You can provide multiple variables, separated by commas (,).
    test_vars: Tumor Location (Primary vs LN)

    # [Required] The column name(s) in the sample annotation (given by {sample_annotation_file}) corresponding to 
    # the variables to be used for the random intercept in the linear mixed models for differential expression.
    # You can provide multiple variables, separated by commas (,).
    random_intercept_vars: Patient ID

    # [Required] The column name(s) in the sample annotation (given by {sample_annotation_file}) corresponding to 
    # the variables to be used for the random slope in the linear mixed models for differential expression.
    # You can provide multiple variables, separated by commas (,).
    # NOTE: If you are not using a random slope, enter "none".
    random_slope_vars: none

  # ----------------------------------------------------------------------
  #     Miscellaneous settings
  # ----------------------------------------------------------------------
  misc:

    # [Optional] Random seed to be used in algorithms that use stochastic processes (e.g. UMAP).
    # If not provided, it will default to 1026. 
    random_seed: 1026