name: geomx
channels:
  - conda-forge
  - bioconda
  - defaults
  - R
dependencies: 
  - conda-forge::r-base=4.3.1
  - conda-forge::rstudio-desktop=2022.12.0
  - conda-forge::r-tidyverse=2.0.0
  - conda-forge::r-dplyr=1.1.3
  - bioconda::bioconductor-nanostringnctools=1.10.0 
  - bioconda::bioconductor-geomxtools=3.5.0
  - conda-forge::r-knitr=1.45
  - conda-forge::r-ggforce=0.4.2
  - conda-forge::r-scales=1.3.0
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-cowplot=1.1.3
  - conda-forge::r-umap=0.2.10.0
  - conda-forge::r-rtsne=0.17
  - conda-forge::r-officer=0.6.5
  - conda-forge::radian=0.6.12
  - conda-forge::r-yaml=2.3.8
  - conda-forge::r-shiny=1.8.0
  - conda-forge::r-ggrepel=0.9.5
  - conda-forge::r-matrix=1.6_3
  - bioconda::snakemake=8.7.0